### ISSUE TITLE
Problem with building on CentOS 7.8

### ISSUE THREAD

**Issue by matuszewski** [dogtagpki/pki#3392]
Regardless of which branch I put instead of master `dnf copr enable @pki/master` tells:
**Error: This repository does not have any builds yet so you cannot enable it now.**
But I guess it surely does

**Comment by cipherboy** [comment]
Hi @matuszewski -- it is unlikely that any branch newer than `DOGTAG_10_5_BRANCH` will support building on CentOS/RHEL 7. This is because many dependencies (including CMake) are newer on RHEL 8 and are used by Dogtag v10.6 and above.

This error is telling you that, while the COPR does have builds, it does not have any repos for CentOS 7.8 with builds in it.

**Comment by matuszewski** [comment]
Ok, I get it now. Thanks! :)
