### ISSUE TITLE
CI on older branches fails due to EOL Fedora builds being unavailable

### ISSUE THREAD

**Issue by ckelleyRH** [dogtagpki/pki#4238]
F34 builds are not building in the PKI COPR repo, this is causing [CI failures](https://github.com/dogtagpki/pki/actions?query=branch%3Av10.13++) in `v10.13` branch.

Interestingly `v10.12` and `v10.14` are both fine. We should find some solution for restoring these builds.

**Comment by celestian** [comment]
Internal ticket https://issues.redhat.com/browse/RHCS-3511

**Comment by edewata** [comment]
This is already fixed in `v10`, `v10.14`, and `v10.13` branches. The `master` branch has also been updated to use the same mechanism.

Now builds are published to `*-dist` images under https://quay.io/organization/dogtagpki and the CI will get the builds from these images to run the tests. Builds will continue to be created on COPR repos, but they are no longer used for CI.
