### ISSUE TITLE
CA creation fails on Debian when installing FreeIPA Server

### ISSUE THREAD

**Issue by Nihlus** [dogtagpki/pki#4334]
I'm currently trying to assist with getting FreeIPA packaged and working on Debian, but I'm running into trouble with dogtag during installation of the server component. In short, pki-tomcatd@pki-tomcat refuses to start after I reach the TLS configuration step for dirsrv, and with some help from the FreeIPA IRC channel I've traced the problem to some sort of issue with the certificates and keys created during CA setup.

Essentially, one or more certificates and/or keys are missing (usually Server-Cert) after the installation step and it's very unclear why. To add to the problem, the issue is not stable in its expression, and different certs or keys can be missing after the installation fails; other times, the installation does succeed and results in a fully functional FreeIPA server.

## System information
OS: Debian 11 Bullseye
dogtag-pki version: 11.2.1
FreeIPA version: 4.9.11
Installed packages: [installed-packages.log](https://github.com/dogtagpki/pki/files/10786934/installed-packages.log)

## Prerequisites
* Built packages of FreeIPA, dogtag and their dependencies (can be provided or packages from Debian Testing used)
* Debian 11 installation or VM

## Steps to reproduce
1. Install freeipa-server
2. Run `sudo ipa-server-install -p ipa_admin -a ipa_admin --ip-address <IP> -n domain -r DOMAIN --hostname some.domain --setup-dns --auto-reverse --auto-forwarders -U`
3. Observe failure after `configuring TLS for DS instance`

## Logs & Info
I am, to be perfectly honest, wayyy out of my depth with this, but I've been gathering what information I can to try and figure the issue out.

https://gist.github.com/Nihlus/fa55566886c2d01a7ab5f7e17c01eeb9 contains most of the relevant logs. 
https://gist.github.com/Nihlus/39924be3bdbcbafbb0c73aab0f126027 contains some inspections of the various CA certificates and key databases after a failed run. https://gist.github.com/Nihlus/b4dda1796b81018f88c78f93533ea093 is another, later failed run with similar information.

I can also provide VM images upon request if a deeper dive is of interest. I'd be happy to provide any additional information needed.

**Comment by tjaalton** [comment]
you should use unstable all the way to rule out differences in java versions etc

**Comment by tjaalton** [comment]
that said, I've seen this issue myself in the past

**Comment by edewata** [comment]
Hi, according to this log `pkispawn` completed PKI installation and started PKI server successfully (which meant the certs were complete):
https://gist.github.com/Nihlus/fa55566886c2d01a7ab5f7e17c01eeb9#file-ipaserver-install-log-L6225-L6244

After PKI installation, IPA performed several operations (which I'm not too familiar with) on PKI server, then tried to restart PKI server, which failed due to a missing cert. Is it possible for you (maybe with some help from IPA team) to retest and check whether the certs are still intact **before** PKI server is restarted?

If the certs are still intact before restart, that means somehow the certs got deleted during restart, which could be a bug in PKI. However, if there's a missing cert before restart, that probably means there's a bug in IPA.

**Comment by edewata** [comment]
@rcritten @ckelleyRH @celestian

**Comment by rcritten** [comment]
I think you can probably embed a bunch of calls in cainstance.py in each installing from __spawn_instance on with something like:

db = certs.CertDB(self.realm, nssdir=paths.PKI_TOMCAT_ALIAS_DIR)
db.list_certs()

Personally I'd start with one immediately after DogtagInstance.spawn_instance and work from there.

**Comment by Nihlus** [comment]
I've spent some time trying that, but with no apparent luck - the certificates all seem fine throughout every step of cainstance.py's process. `list_certs` consistently prints the following:

```
Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

caSigningCert cert-pki-ca                                    CTu,Cu,Cu
ocspSigningCert cert-pki-ca                                  u,u,u
subsystemCert cert-pki-ca                                    u,u,u
auditSigningCert cert-pki-ca                                 u,u,Pu
Server-Cert cert-pki-ca                                      u,u,u
```

Is there some kind of in-memory cache that we might be losing when the PKI server restarts?

**Comment by Nihlus** [comment]
Looking through the files, the Fedora service file for pki-tomcatd differs from the one used in Debian. While I haven't been able to determine if this is a cause or component of the problem, it is something to take a look at. Notably, the Debian variant runs the Catalina server in the foreground (using the `run` command) while the Fedora service appears to use the forking variant with `start` and `stop` (though the service file's type is `simple`, so I might be barking up an irrelevant tree).

Thoughts on that?

**Comment by edewata** [comment]
Thanks for the info. So it looks like the certs are disappearing after the restart. Does IPA run any external processes (e.g. certmonger, custodia, cert-fix) that might touch PKI's NSS database while PKI server is running? Is it possible to disable them so we can isolate the problem?

I'm not sure about the systemd differences between Fedora and Debian, but I doubt it's causing this problem.

**Comment by Nihlus** [comment]
I'll have to defer to @rcritten on that one - I'm not familiar enough with IPA's setup process to say for certain. I do know certmonger is involved at some point, but if I recall correctly it's further down the installation pipeline.

**Comment by rcritten** [comment]
I ran `inotifywait -m /etc/pki/pki-tomcat/alias/cert9.db` during installation, starting right after pkispawn was done (I added a pdb to pause the install and in another window I fired up inotifyway). There were a few CLOSE_WRITE but this doesn't necessarily mean a write was done, just that the file was opened read/write and then closed. There were no ATTRIB which means some metadata of the file changed so I think it's safe to say that no writes were done at all post-install.

Using stat(1) against the db files may also provide clues when they were created, modifed, etc. You could, for example, add a pdb after the spawn and then use chattr to make the NSS database immutable and see if something blows up.

**Comment by Nihlus** [comment]
I dove back down into cainstance.py and its operations - the results didn't quite sit right with me, and looking at the process list at the same time the installation is running, I can see several operations running concurrently with steps in the installer.

As far as I can tell the installation process doesn't wait for everything to be done step-by-step - I dropped a hold right after `configure_instance`'s `finally` at the end, and while I'm held at that point I can see several certmonger processes appearing and disappearing, along with a number of pki-tomcatd restarts. After that whole shebang finishes up, the certificates are indeed destroyed.

By placing more stops (using `input()` in my case) along each step and waiting for the certmonger and pki-tomcat processes to stabilize before advancing to the next step, I have found the point where the certificates are destroyed - it's in step 20, `configure certificate renewals`. Before that step runs, all of the certs are OK on disk, and after it, they're shot.

This step calls `DogtagInstance::configure_renewal`, which is a loop of `certmonger.start_tracking` calls. Pausing after each loop iteration and allowing the system to stabilize doesn't help, but it appears that the second iteration of the loop is what kills it. After that point, pki-tomcat fails to initialize the CA subsystem and will not start.

Iteration 1:
```
Listing certificates in pki-tomcat...

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

caSigningCert cert-pki-ca                                    CTu,Cu,Cu
ocspSigningCert cert-pki-ca                                  u,u,u
subsystemCert cert-pki-ca                                    u,u,u
Server-Cert cert-pki-ca                                      u,u,u
auditSigningCert cert-pki-ca                                 u,u,Pu

Listing key IDs in pki-tomcat...
certutil: Checking token "NSS Certificate DB" in slot "NSS User Private Key and Certificate Services"
< 0> rsa      dff5dc78adfb30fa47c080dbf6cf377d16714a96   NSS Certificate DB:Server-Cert cert-pki-ca
< 1> rsa      350229f35fcf991601aa958269571a03aedad931   NSS Certificate DB:caSigningCert cert-pki-ca
< 2> rsa      9c8cd807b45641144c73d2218a54c3ff2a6c3f1e   NSS Certificate DB:ocspSigningCert cert-pki-ca
< 3> rsa      48c0f28e29a0986904e8f1a91599f3650a2c6ca1   NSS Certificate DB:subsystemCert cert-pki-ca
< 4> rsa      cc0821ed40def50978c542fde3a456fa6820cb0a   NSS Certificate DB:auditSigningCert cert-pki-ca

Checking pki-tomcat certificate validity as SSL server...
certutil: certificate is valid
```

Iteration 2:
```
Listing certificates in pki-tomcat...

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

caSigningCert cert-pki-ca                                    CTu,Cu,Cu
subsystemCert cert-pki-ca                                    u,u,u
Server-Cert cert-pki-ca                                      u,u,u
ocspSigningCert cert-pki-ca                                  u,u,u

Listing key IDs in pki-tomcat...
certutil: Checking token "NSS Certificate DB" in slot "NSS User Private Key and Certificate Services"
< 0> rsa      dff5dc78adfb30fa47c080dbf6cf377d16714a96   NSS Certificate DB:Server-Cert cert-pki-ca
< 1> rsa      350229f35fcf991601aa958269571a03aedad931   NSS Certificate DB:caSigningCert cert-pki-ca
< 2> rsa      9c8cd807b45641144c73d2218a54c3ff2a6c3f1e   NSS Certificate DB:ocspSigningCert cert-pki-ca
< 3> rsa      48c0f28e29a0986904e8f1a91599f3650a2c6ca1   NSS Certificate DB:subsystemCert cert-pki-ca

Checking pki-tomcat certificate validity as SSL server...
certutil: certificate is valid
```

**Comment by Nihlus** [comment]
Note that this is a check from outside the ipa-server-install process - I'm doing a manual certutil run on the databases instead of utilizing the `db.list_certs` method.

**Comment by rcritten** [comment]
db.list_certs() forks out to certutil.

I think you'll need to look at the journal. start-tracking will read the certs for subject, etc but otherwise shouldn't mess with them. What version of certmonger is this? I'd also set at least a debug level of 2 on certminger, if not 3. Any higher than that is counterproductive.

**Comment by Nihlus** [comment]
I'm using certmonger 0.79.16 at the moment. Here's the log up until the point where pki-tomcat dies - seems like certmonger is removing a cert whose CN is `localhost`, which seems strange.
[certmonger.log](https://github.com/dogtagpki/pki/files/10807132/certmonger.log)

**Comment by rcritten** [comment]
The problem appears to be in "Unable to initialize NSS" which means certmonger can't read the existing certificate so it tries to generate a new one. It doesn't seem to be permissions-related but it could be affected by things like SELinux and I suppose AppArmor.

**Comment by Nihlus** [comment]
I don't have SELinux or AppArmor installed, so we can rule those out - are there any paths or settings in particular that could affect NSS initialization?

**Comment by rcritten** [comment]
I'm sure all kinds of things could affect it. certmonger actually initializes it twice. Once to shake our permission and access issues and then finally if all that was successful. Iv'e never seen it fail here. Since there is no logging around the reason for failure the brute force approach would be to strace -f the certmonger process to see what is happening just prior to the init failure.

**Comment by Nihlus** [comment]
Right, gotcha - here's a run with strace and its accompanying journald log. 

[certmonger-logs.tar.gz](https://github.com/dogtagpki/pki/files/10808038/certmonger-logs.tar.gz)

**Comment by rcritten** [comment]
It's hard to tell what is going on in the strace because the strings are very short. Can you re-run it with -s 1024?

Can you also provide the files in /var/lib/certmonger/requests?

**Comment by Nihlus** [comment]
Alright, here's today's logs - interestingly, I had two successful runs before I saw the error again, so we have something to compare with too. The files are pretty large, so they're over here: https://algiz.nu/nextcloud/s/dFrJXsWeHRdaY2T

**Comment by rcritten** [comment]
Can you see if there is an NSS database in /etc/pki/nssdb? If not try this and installing to see if it helps:

`certutil -N -d /etc/pki/nssdb --empty-password`

**Comment by Nihlus** [comment]
That directory was indeed empty - creating a database there with the command does appear to resolve the issue! I've performed four uninstall/install sequences now without a single failure, so it looks very promising. Can you elaborate on the problem and why this particular solution helped?

**Comment by rcritten** [comment]
For parsing an existing certificate certmonger uses the default NSS database (/etc/pki/nssdb) as its context. Since the database didn't exist, no parse, and it was treated as a failure. I'm still not sure why sometimes you saw success but even in the "good" cases bad things happened.

On Fedora/RHEL the /etc/pki/nssdb database is provided by the nss package.

It looks like it does this because it treats parsing a PEM certificate as a standalone operation and not within the context of any specific database.

I'm going to improve the error message to at least include the database that wasn't initialized to leave a crumb as to what is happening.

**Comment by Nihlus** [comment]
Aha, I see. A packaging bug on the NSS package sounds like it'd be in order, then. I'll get to writing that and put together a postinstall patch in the meantime.

**Comment by tjaalton** [comment]
thanks for finding the culprit :)

that said, I don't think it's realistic to get libnss3 ship the db on Debian, iirc that has been asked in the past and nothing changed. Maybe certmonger just needs to create it in postinst if it doesn't exist yet.

**Comment by Nihlus** [comment]
Either that or as part of FreeIPA's installation process - though it'd be nicer if NSS sorted it out in their end, considering this doesn't appear to be the only project affected by it.

**Comment by tjaalton** [comment]
seems like you found the bug (#798455), it's good to see what Mike replies, if he does..

anyway, this dogtag issue can be closed now

**Comment by tjaalton** [comment]
I'll add a private nssdb to the certmonger package, and make sure it uses that and not /etc/pki/nssdb

**Comment by rcritten** [comment]
For parsing an existing certificate certmonger uses the default NSS database (/etc/pki/nssdb) as its context. Since the database didn't exist, no parse, and it was treated as a failure. I'm still not sure why sometimes you saw success but even in the "good" cases bad things happened.

On Fedora/RHEL the /etc/pki/nssdb database is provided by the nss package.

It looks like it does this because certmonger treats parsing a PEM certificate as a standalone operation and not within the context of any specific database.

I'm going to improve the error message to at least include the database that wasn't initialized to leave a crumb as to what is happening.

**Comment by rcritten** [comment]
Sigh, FF "helpfully" kept the same message after restarting and posted it.

I'll mark this as done.

**Comment by edewata** [comment]
Hi, could anybody show me the code that removes the CN=localhost certificate? I think IPA/certmonger should not access/modify PKI's NSS database directly since it could lead to issues like this that we cannot support, so I'm trying to see if there's a better way to do that.

**Comment by rcritten** [comment]
certmonger requires write access to the database to add updated certificates for renewals and updating replicas.

The path is rather convoluted. It begins with the IPA installer calling certmonger to start tracking the already issued CA certificates. As part of this certmonger reads the certificate to parse out subject, issuer, serial number, etc.

This happens in https://pagure.io/certmonger/blob/master/f/src/certread-n.c#_291. At line 303 the default system NSS database is opened and used as context for reading the cert blob and parsing it. The problem is that in the case of Debian there was no database there so the open failed and the parser returned 1.

certmonger's state machine interpreted that as "there is no certificate" so issued a new CSR which used subject cn=localhost. This would happen repeatedly sometimes. I can't explain why the IPA installation was sometimes successful because even on a "good" run the journal was filled with certmonger looping.

certmonger can't necessarily fall back to the database that the certificate resides in because it uses this method to parse all certificates, even for OpenSSL, so there may not be a DB. I currently have a PR to fall back to the "real" NSS database if there is one if the open fails, otherwise use NULL which is the equivalent of NSS_NoDB_Init. I'm leaning towards just always using the latter because this particular operation is always read-only and only used to parse out fields from the certificate PEM.

The code in question dates back to 2009 and has always worked because the Fedora/RHEL packaging has always provided a default NSS database. Apparently the Debian nss packaging does not.

**Comment by edewata** [comment]
Thanks for the clarification. I think there are two issues here:

* missing default system NSS database on Debian ([Debian Bug #798455](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=798455))
* certmonger reading and writing PKI's NSS database while PKI server is running

Even if the first issue is fixed on Debian, we still have the second issue which could affect all platforms.

When PKI server is started, it tries to load and validate the required certs. At the same time, certmonger tries to renew the certs, and due to the first issue it ends up removing one of the certs. Since there's no coordination between PKI and IPA/certmonger, sometimes it could work or break, depending on timing or other factors. I think we need to define the protocol for updating the certs in PKI to avoid these issues.

**Comment by rcritten** [comment]
It doesn't work that way. certmonger, via IPA-provided pre-save scripts, stops PKI before updating the NSS database with updated certificates. It's safe.

**Comment by edewata** [comment]
Oh OK, I was under the impression that the cert disappeared after restart, but I guess I didn't read it correctly. As long as PKI is stopped during NSS database update it should be fine. Thanks!
