### ISSUE TITLE
CA configuration failed on IPA server. (@pki/master)

### ISSUE THREAD

**Issue by amore17** [dogtagpki/pki#4891]
The installation of a CA fails on a server when the @pki/master copr repository is enabled.

The error can be seen in FreeIPA nightly tests, for instance in PR #https://github.com/freeipa-pr-ci2/freeipa/pull/4130 with the 
[report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/562587d6-9a3b-11ef-b5ee-fa163ed62e73/report.html?sort=result) and [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/562587d6-9a3b-11ef-b5ee-fa163ed62e73/test_integration-test_uninstallation.py-TestUninstallBase-install/master.ipa.test/var/log/pki/)

**Comment by flo-renaud** [comment]
The issue was introduced with this commit: https://github.com/dogtagpki/pki/commit/596ea567a81170c03304ce5ec8080e4aa8d85c30

The commit is using the methods `not_valid_before_utc` / `not_valid_after_utc` but they were introduced with python-cryptography 42.0.0 (https://cryptography.io/en/latest/x509/reference/#cryptography.x509.Certificate.not_valid_before_utc) and the test is running on Fedora 40 with python-cryptography-41.0.7-1.fc40

**Comment by edewata** [comment]
The issue should be fixed in https://github.com/dogtagpki/pki/commit/16a100405ca5e8d7719ccc68f98f220cbdfa0a08.

Could you try again? Thanks.

**Comment by flo-renaud** [comment]
The issue has been fixed, latest run shows better results: https://github.com/freeipa-pr-ci2/freeipa/pull/4148
