### ISSUE TITLE
Building guide does not work

### ISSUE THREAD

**Issue by stlaz** [dogtagpki/pki#6]
Read:
http://pki.fedoraproject.org/wiki/Building_Dogtag_10

Tried:
1. `git clone git@github.com:dogtagpki/pki.git dogtagpki`
2. `cd scripts`
3. `./compose_pki_core_packages rpms`

Got:
```
error: Unable to open pki/specs/pki-core.spec: No such file or directory
ERROR:  'pki/specs/pki-core.spec' is missing!


Usage:  ./compose_pki_core_packages [options] <target>

        where <target> is one of the following:
...
```

**Comment by SilleBille** [comment]
The issue has been fixed in commit: https://github.com/dogtagpki/pki/tree/4bc4f9a385f0ad20edfede06e6bf0849da6a26db

The directory name should be `pki` and not `dogtagpki`.

Verified in the local machine. 
Steps:
1.    git clone https://github.com/dogtagpki/pki.git
2.    cd pki/scripts
3.   ./compose_pki_core_packages rpms
